"""add watchlist groups

Revision ID: 11b05ec9dfbc
Revises: f6900470b6e1
Create Date: 2026-06-18 15:09:53.778050

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11b05ec9dfbc"
down_revision: str | Sequence[str] | None = "f6900470b6e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlist_groups",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_group_user_name"),
    )
    op.create_index(
        op.f("ix_watchlist_groups_user_id"), "watchlist_groups", ["user_id"], unique=False
    )
    op.create_table(
        "watchlist_group_members",
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["watchlist_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "symbol"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watchlist_group_members")
    op.drop_index(op.f("ix_watchlist_groups_user_id"), table_name="watchlist_groups")
    op.drop_table("watchlist_groups")
    # ### end Alembic commands ###
